[package]
name = "morsite"
version = "0.1.0"
authors = ["Shaurya Shubham <shauryashubham1234567890@gmail.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.11"
maplit = "1.0"
